services:
  application:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env.local
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - main-network

  redis:
    image: redis:8.6.1
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    networks:
      - main-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  mongo:
    image: mongo:8.2.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABSE}
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - main-network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  main-network:
